# Generated by Django 3.1 on 2020-09-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='area_hectares',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
